services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: money_manager
    volumes:
      - .:/var/www/html
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:IlrLDdcCuwtkHSkm2FJuUNvQ7ACyyuTbMY8J/3XKUd0=
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: money_manager
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: postgres:16-alpine
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_DB: money_manager
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
